l_french:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
 pm_primary:0 "Enseignement primaire"
 pmg_secondary_building_rye_farm:0 "Secondaire"
 pmg_secondary_building_wheat_farm:0 "Secondaire"
 pmg_secondary_building_rice_farm:0 "Secondaire"
 pmg_secondary_building_maize_farm:0 "Secondaire"
 pmg_secondary_building_millet_farm:0 "Secondaire"
 pm_no_secondary:0 "Maintenir une seule culture"
 pm_potatoes:0 "Pommes de terre"
 pm_vineyards:0 "Vignobles"
 pm_vineyards_building_maize_farm:0 "Vignobles"
 pm_apple_orchards:0 "Les vergers de pommes"
 pm_citrus_orchards:0 "Citrons"
 pm_fig_orchards:0 "Figuiers"
 pm_fig_orchards_building_rice_farm:0 "Figuiers"
 pm_mulberry_groves:0 "Mûres"

 pmg_train_automation_building_vineyard_plantation:0 "Transports"
 pmg_base_building_vineyard_plantation:0 "Production"
 default_building_vineyard_plantation:0 "Production de base"
 automatic_irrigation_building_vineyard_plantation:0 "OGM"
 
 pmg_automation:0 "Automatisation"
 pmg_automation_building_food_industry:0 "Automatisation"
 pmg_automation_building_textile_mills:0 "Automatisation"
 pmg_automation_building_furniture_manufactory:0 "Automatisation"
 pmg_automation_building_tooling_workshops:0 "Automatisation"
 pmg_automation_building_paper_mills:0 "Automatisation"
 pmg_automation_building_steel_mills:0 "Automatisation"
 pmg_automation_building_motor_industry:0 "Automatisation"
 pm_civilian_priority:0 "Priorité civile"
 pm_military_priority:0 "Priorité militaire"

  # Textile Mills
 pm_craftsman_sewing:0 "Production de luxe"
 pm_sewing_machines:0 "Couture automatisée"
 pm_electric_sewing_machines:0 "Vêtements imprimés 3D"
 pm_traditional_looms:0 "Pois mécanisés"
 pm_mechanized_looms:0 "Poignées robotiques"
 pm_automatic_power_looms:0 "Des déporteurs"

  # Glassworks
 pm_leaded_glass:0 "Verre de fusion"
 pm_manual_glassblowing:0 "Moulage par étincelles"

  # Chemical Plants
 pm_leblanc_process:0 "Électrolyse saline"
 pm_no_explosives_production:0 "Privilégier la production chimique"
 pm_ammonia-soda_process:0 "Smart Bombs"
 pm_vacuum_evaporation:0 "Bombes à laser"
 pm_brine_electrolysis:0 "Bombe antimatière"
 pmg_fertilizer_production:0 "Production chimique"
 pm_no_artificial_fertilizers:0 "Pas d'engrais artificiels"
 pm_artificial_fertilizers:0 "Fixation de l'azote"
 pm_improved_fertilizer:0 "Processus Haber-Bosch"
 pm_nitrogen_fixation:0 "Synthèse de l'ammoniac"
 pm_dyes_production:0 "Production de colorants"
 pm_no_synthetic_dyes:0 "Pas de colorant synthétique"
 pmg_synthetic_dyes:0 "colorants synthétiques"
 pm_silk_production:0 "Production de soie"
 pm_no_artificial_fibers:0 "Privilégier la production de colorants"
 pm_rayon:0 "Rayon"

  # Foundries
 pm_steamworks:0 "Usines à vapeur"
 pm_no_artillery_production:0 "Privilégier la production d ' armes légères"
 pm_artillery_production:0 "Production d'artillerie"

  # Motor Industries
 pmg_automobile_production:0 "Production de masse"
 pm_mass_automobile_production:0 "Moteurs"
 pm_automobile_production:0 "Production automobile"

## SMD

pm_no_chip_production:0 "Ligne d'assemblage des puces"
pm_robotic_assembly:0 "Assemblage de la puce robotique"
pm_nanobot_assembly:0 "Montage des puces de nanobot"
pm_3d_printed_chips:0 "Chips imprimés 3D"

pm_synthetic_rubber:0 "Caoutchouc synthétique"
