l_turkish:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
 pm_primary:0 "İlk önce birincil birincil birincil birincil"
 pmg_secondary_building_rye_farm:0 "Secondary Secondary Secondary Secondary Secondary Secondary"
 pmg_secondary_building_wheat_farm:0 "Secondary Secondary Secondary Secondary Secondary Secondary"
 pmg_secondary_building_rice_farm:0 "Secondary Secondary Secondary Secondary Secondary Secondary"
 pmg_secondary_building_maize_farm:0 "Secondary Secondary Secondary Secondary Secondary Secondary"
 pmg_secondary_building_millet_farm:0 "Secondary Secondary Secondary Secondary Secondary Secondary"
 pm_no_secondary:0 "Single Crop"
 pm_potatoes:0 "Potatoes"
 pm_vineyards:0 "Vineyards"
 pm_vineyards_building_maize_farm:0 "Vineyards"
 pm_apple_orchards:0 "Apple Orchards"
 pm_citrus_orchards:0 "Citrus Orchards"
 pm_fig_orchards:0 "Fig Orchards"
 pm_fig_orchards_building_rice_farm:0 "Fig Orchards"
 pm_mulberry_groves:0 "Mulberry Groves"

 pmg_train_automation_building_vineyard_plantation:0 "Ulaşım Ulaşım"
 pmg_base_building_vineyard_plantation:0 "Prodüksiyon Prodüksiyon"
 default_building_vineyard_plantation:0 "Temel Üretim Temel Üretim"
 automatic_irrigation_building_vineyard_plantation:0 "GMOs"
 
 pmg_automation:0 "Otomasyon"
 pmg_automation_building_food_industry:0 "Otomasyon"
 pmg_automation_building_textile_mills:0 "Otomasyon"
 pmg_automation_building_furniture_manufactory:0 "Otomasyon"
 pmg_automation_building_tooling_workshops:0 "Otomasyon"
 pmg_automation_building_paper_mills:0 "Otomasyon"
 pmg_automation_building_steel_mills:0 "Otomasyon"
 pmg_automation_building_motor_industry:0 "Otomasyon"
 pm_civilian_priority:0 "Sivil Öncelik"
 pm_military_priority:0 "Askeri Öncelik"

  # Textile Mills
 pm_craftsman_sewing:0 "Lüks Üretim"
 pm_sewing_machines:0 "Otomatik kaplama"
 pm_electric_sewing_machines:0 "3D Bas Giyim"
 pm_traditional_looms:0 "Mekanik Looms"
 pm_mechanized_looms:0 "Robotik Looms"
 pm_automatic_power_looms:0 "Dropshippers"

  # Glassworks
 pm_leaded_glass:0 "Fusion Glass"
 pm_manual_glassblowing:0 "Titreşimli kalıp"

  # Chemical Plants
 pm_leblanc_process:0 "Brine"
 pm_no_explosives_production:0 "Kimyasal Üretimin Önceliği"
 pm_ammonia-soda_process:0 "Smart Bombs"
 pm_vacuum_evaporation:0 "Laser-Guided Bombs"
 pm_brine_electrolysis:0 "Antimatter Bomb"
 pmg_fertilizer_production:0 "Kimyasal Üretim"
 pm_no_artificial_fertilizers:0 "Yapay gübre yok"
 pm_artificial_fertilizers:0 "Nitrojen Fixation"
 pm_improved_fertilizer:0 "News-Bosch Process"
 pm_nitrogen_fixation:0 "Ammonia Synthesis"
 pm_dyes_production:0 "Dyes Production"
 pm_no_synthetic_dyes:0 "Hiçbir Sentetik Dyes"
 pmg_synthetic_dyes:0 "Sentetik Dyes"
 pm_silk_production:0 "Silk Production"
 pm_no_artificial_fibers:0 "Önce Dye Production"
 pm_rayon:0 "Göğüs"

  # Foundries
 pm_steamworks:0 "Buhar işleri"
 pm_no_artillery_production:0 "Küçük Silah Üretimi Önce"
 pm_artillery_production:0 "Artillery Production"

  # Motor Industries
 pmg_automobile_production:0 "Mass Production"
 pm_mass_automobile_production:0 "Motor Santralleri"
 pm_automobile_production:0 "Otomobil Üretimi"

## SMD

pm_no_chip_production:0 "Chip Assembly Line"
pm_robotic_assembly:0 "Robotik Chip Assembly"
pm_nanobot_assembly:0 "Nanobot Chip Assembly"
pm_3d_printed_chips:0 "3D Baslı Chips"

pm_synthetic_rubber:0 "Sentetik Kauçuk"
