l_japanese:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
 pm_primary:0 "プライマー"
 pmg_secondary_building_rye_farm:0 "セカンダリー"
 pmg_secondary_building_wheat_farm:0 "セカンダリー"
 pmg_secondary_building_rice_farm:0 "セカンダリー"
 pmg_secondary_building_maize_farm:0 "セカンダリー"
 pmg_secondary_building_millet_farm:0 "セカンダリー"
 pm_no_secondary:0 "シングルクロップを維持"
 pm_potatoes:0 "ポテト"
 pm_vineyards:0 "ワイナリー"
 pm_vineyards_building_maize_farm:0 "ワイナリー"
 pm_apple_orchards:0 "アップルオーチャード"
 pm_citrus_orchards:0 "シトラスオーチャード"
 pm_fig_orchards:0 "図オーチャード"
 pm_fig_orchards_building_rice_farm:0 "図オーチャード"
 pm_mulberry_groves:0 "マルベリー・グローブズ"

 pmg_train_automation_building_vineyard_plantation:0 "交通アクセス"
 pmg_base_building_vineyard_plantation:0 "生産工程"
 default_building_vineyard_plantation:0 "基礎生産"
 automatic_irrigation_building_vineyard_plantation:0 "GMOス"
 
 pmg_automation:0 "オートメーション"
 pmg_automation_building_food_industry:0 "オートメーション"
 pmg_automation_building_textile_mills:0 "オートメーション"
 pmg_automation_building_furniture_manufactory:0 "オートメーション"
 pmg_automation_building_tooling_workshops:0 "オートメーション"
 pmg_automation_building_paper_mills:0 "オートメーション"
 pmg_automation_building_steel_mills:0 "オートメーション"
 pmg_automation_building_motor_industry:0 "オートメーション"
 pm_civilian_priority:0 "市民優先順位"
 pm_military_priority:0 "軍隊の優先順位"

  # Textile Mills
 pm_craftsman_sewing:0 "贅沢な生産"
 pm_sewing_machines:0 "自動縫製"
 pm_electric_sewing_machines:0 "3Dプリント服"
 pm_traditional_looms:0 "メカニックローム"
 pm_mechanized_looms:0 "ロボットローム"
 pm_automatic_power_looms:0 "ドロップシッパー"

  # Glassworks
 pm_leaded_glass:0 "融合ガラス"
 pm_manual_glassblowing:0 "押出ブロー成形"

  # Chemical Plants
 pm_leblanc_process:0 "塩水電解"
 pm_no_explosives_production:0 "化学生産の優先化"
 pm_ammonia-soda_process:0 "Smart Bombs"
 pm_vacuum_evaporation:0 "レーザー誘導爆弾"
 pm_brine_electrolysis:0 "防火爆弾"
 pmg_fertilizer_production:0 "化学生産"
 pm_no_artificial_fertilizers:0 "人工的な肥料無し"
 pm_artificial_fertilizers:0 "窒素の固定"
 pm_improved_fertilizer:0 "Haber-Boschプロセス"
 pm_nitrogen_fixation:0 "アンモナル合成"
 pm_dyes_production:0 "染料の生産"
 pm_no_synthetic_dyes:0 "合成染料なし"
 pmg_synthetic_dyes:0 "合成染料"
 pm_silk_production:0 "絹の生産"
 pm_no_artificial_fibers:0 "染料の生産を優先します"
 pm_rayon:0 "レイヨン"

  # Foundries
 pm_steamworks:0 "スチームワークス"
 pm_no_artillery_production:0 "小さな腕の生産を優先"
 pm_artillery_production:0 "アーチェリーの生産"

  # Motor Industries
 pmg_automobile_production:0 "大量生産"
 pm_mass_automobile_production:0 "モータープラント"
 pm_automobile_production:0 "自動車生産"

## SMD

pm_no_chip_production:0 "チップ組立ライン"
pm_robotic_assembly:0 "ロボットチップアセンブリ"
pm_nanobot_assembly:0 "ナノボットチップアセンブリ"
pm_3d_printed_chips:0 "3Dプリントチップ"

pm_synthetic_rubber:0 "合成ゴム"
