l_braz_por:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
 pm_primary:0 "Primário"
 pmg_secondary_building_rye_farm:0 "Secundário"
 pmg_secondary_building_wheat_farm:0 "Secundário"
 pmg_secondary_building_rice_farm:0 "Secundário"
 pmg_secondary_building_maize_farm:0 "Secundário"
 pmg_secondary_building_millet_farm:0 "Secundário"
 pm_no_secondary:0 "Manter uma única colheita"
 pm_potatoes:0 "Batatas"
 pm_vineyards:0 "Vinhas"
 pm_vineyards_building_maize_farm:0 "Vinhas"
 pm_apple_orchards:0 "Orchards de maçã"
 pm_citrus_orchards:0 "Citrus Orchards"
 pm_fig_orchards:0 "Orchards de figo"
 pm_fig_orchards_building_rice_farm:0 "Orchards de figo"
 pm_mulberry_groves:0 "Bagas de amoreira"

 pmg_train_automation_building_vineyard_plantation:0 "Transportes"
 pmg_base_building_vineyard_plantation:0 "Produção"
 default_building_vineyard_plantation:0 "Produção de base"
 automatic_irrigation_building_vineyard_plantation:0 "OGM"
 
 pmg_automation:0 "Automação"
 pmg_automation_building_food_industry:0 "Automação"
 pmg_automation_building_textile_mills:0 "Automação"
 pmg_automation_building_furniture_manufactory:0 "Automação"
 pmg_automation_building_tooling_workshops:0 "Automação"
 pmg_automation_building_paper_mills:0 "Automação"
 pmg_automation_building_steel_mills:0 "Automação"
 pmg_automation_building_motor_industry:0 "Automação"
 pm_civilian_priority:0 "Prioridade Civil"
 pm_military_priority:0 "Prioridade Militar"

  # Textile Mills
 pm_craftsman_sewing:0 "Produção de Luxo"
 pm_sewing_machines:0 "Costura automatizada"
 pm_electric_sewing_machines:0 "Vestuário impresso em 3D"
 pm_traditional_looms:0 "Teares Mecanizados"
 pm_mechanized_looms:0 "Teares Robóticos"
 pm_automatic_power_looms:0 "Transportadores"

  # Glassworks
 pm_leaded_glass:0 "Vidro de Fusão"
 pm_manual_glassblowing:0 "Moldagem por sopro de extrusão"

  # Chemical Plants
 pm_leblanc_process:0 "Electrólise brina"
 pm_no_explosives_production:0 "Priorizar a Produção Química"
 pm_ammonia-soda_process:0 "Smart Bombs"
 pm_vacuum_evaporation:0 "Bombas Guiadas por Laser"
 pm_brine_electrolysis:0 "Bomba de Antimatéria"
 pmg_fertilizer_production:0 "Produção química"
 pm_no_artificial_fertilizers:0 "Sem fertilizantes artificiais"
 pm_artificial_fertilizers:0 "Fixação do azoto"
 pm_improved_fertilizer:0 "Processo Haber- Bosch"
 pm_nitrogen_fixation:0 "Síntese da amónia"
 pm_dyes_production:0 "Produção de corantes"
 pm_no_synthetic_dyes:0 "Sem tintas sintéticas"
 pmg_synthetic_dyes:0 "Corantes sintéticos"
 pm_silk_production:0 "Produção de seda"
 pm_no_artificial_fibers:0 "Priorizar a produção de tinta"
 pm_rayon:0 "Rayon"

  # Foundries
 pm_steamworks:0 "Trabalhos a vapor"
 pm_no_artillery_production:0 "Priorizar a produção de armas pequenas"
 pm_artillery_production:0 "Produção de artilharia"

  # Motor Industries
 pmg_automobile_production:0 "Produção em massa"
 pm_mass_automobile_production:0 "Instalações a motor"
 pm_automobile_production:0 "Produção de automóveis"

## SMD

pm_no_chip_production:0 "Linha de montagem de chips"
pm_robotic_assembly:0 "Montagem de Chip Robótica"
pm_nanobot_assembly:0 "Nanobot Chip Assembly"
pm_3d_printed_chips:0 "Chips impressos em 3D"

pm_synthetic_rubber:0 "Borracha sintética"
